# application.properties
server.port=8080
# h2
spring.datasource.url=jdbc:h2:mem:danmakudb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD}
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# MyBatis-Plus
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.type-aliases-package=com.example.danmaku.model
mybatis-plus.global-config.db-config.id-type=auto
# WebSocket
spring.graphql.websocket.keep-alive=8192
spring.graphql.websocket.connection-init-timeout=10000