@baseUrl = http://localhost:8080

### 创建定时任务 - 测试1：创建一个任务
POST {{baseUrl}}/schedule/create
Content-Type: application/x-www-form-urlencoded

time=2026-03-22 21:14:00&message=测试任务1

### 创建定时任务 - 测试3：使用默认消息
POST {{baseUrl}}/schedule/create
Content-Type: application/x-www-form-urlencoded

time=2026-03-22 21:15:00

### 获取所有定时任务列表
GET {{baseUrl}}/schedule/list

### 取消定时任务 - 需要先从列表中获取taskId
POST {{baseUrl}}/schedule/cancel
Content-Type: application/x-www-form-urlencoded

taskId=your-task-id-here

### 测试异常情况：创建过去时间的任务（应该失败）
POST {{baseUrl}}/schedule/create
Content-Type: application/x-www-form-urlencoded

time=2020-01-01 00:00:00&message=过去的任务

### 测试异常情况：取消不存在的任务
POST {{baseUrl}}/schedule/cancel
Content-Type: application/x-www-form-urlencoded

taskId=non-existent-task-id
