spring.application.name=Spring-wxpay
# ??????
wxpay.appId=your_app_id
wxpay.mchId=your_mch_id
wxpay.mchKey=your_mch_key
wxpay.keyPath=classpath:/cert/apiclient_cert.p12
wxpay.notifyUrl=https://yourdomain.com/notify
