server:
  port: 9090

spring:
  mail:
    default-encoding: utf-8  # 默认的邮件编码为UTF-8
    host: smtp.163.com  #配置SMTP服务器地址
    #    port: 994 #端口号 465 或 587
    nickname: 超级帅哥  # 昵称
    username: 18365404517@163.com  #发送邮件的账户
    password: your-email-auth-code # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    properties: # 配置SSL 加密工厂
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true   #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误

#126邮箱SMTP服务器地址:smtp.126.com,端口号:465或者994
#2163邮箱SMTP服务器地址:smtp.163.com,端口号:465或者994
#yeah邮箱SMTP服务器地址:smtp.yeah.net,端口号:465或者994
#qq邮箱SMTP服务器地址：smtp.qq.com,端口号465或587
