server.port=8080
spring.application.name=spring-schedule
server.undertow.threads.worker=64
server.undertow.threads.io=4
server.undertow.buffer-size=1024
server.undertow.direct-buffers=true
logging.level.com.example.demo=DEBUG