server:
  port: 19999

spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: 1
    password: ${DB_PASSWORD}

models:
  gpt:
    api-key: "demo"
    model-name: "gpt-4o-mini"
  wen:
    api-key: "sk-4b6145929a2c40f8870be4f302570c7d"
    model-name: "qwen-plus"
  dsc:
    api-key: "sk-4b6145929a2c40f8870be4f302570c7d"
    model-name: "deepseek-v3"
