minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket-name: default-bucket

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

