spring.application.name=Springboot-data-jpa
server.port=8000
spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.url=jdbc:h2:file:./data/testdb
#spring.datasource.url=jdbc:h2:tcp://localhost/~/testdb
#spring.datasource.url=jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE;DB_LOCK_TIMEOUT=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD}
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.datasource.hikari.auto-commit=true
#spring.datasource.hikari.isolation-level=READ_COMMITTED
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
#spring.sql.init.schema-locations=classpath:schema.sql
