spring.application.name=spring-sse
server.port=8000

spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.url=jdbc:h2:file:./data/testdb
#spring.datasource.url=jdbc:h2:tcp://localhost/~/testdb
#spring.datasource.url=jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE;DB_LOCK_TIMEOUT=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD}

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.hikari.auto-commit=true
#spring.datasource.hikari.isolation-level=READ_COMMITTED
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
#spring.sql.init.schema-locations=classpath:schema.sql

langchain4j.community.dashscope.chat-model.api-key=sk-4b6145929a2c40f8870be4f302570c7d
langchain4j.community.dashscope.chat-model.model-name=qwen-plus
langchain4j.community.dashscope.streaming-chat-model.api-key=sk-4b6145929a2c40f8870be4f302570c7d
langchain4j.community.dashscope.streaming-chat-model.model-name=qwen-plus
