services:
  code-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-runner
    volumes:
      - workspace-data:/workspace
    entrypoint: [ "sh", "-c", "trap 'exit 0' SIGTERM; while :; do sleep 86400 & wait; done" ]
    restart: unless-stopped

volumes:
  workspace-data:
