spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
jwt:
  secret: "your-jwt-secret-key-generate-a-new-one"
  expire: 3600000 * 24        # 24 小时（毫秒）
